alias ll='exa -l --color=always --group-directories-first'
alias lla='exa -la --color=always --group-directories-first'
alias v='vim'
alias s='startx'
alias fm='vifm'
alias pushgit='git add . && git commit -m "1" && git push origin'
alias fullupsys='sudo apt update && sudo apt dist-upgrade && sudo apt clean'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias bottles-cli='flatpak run  --command=bottles-cli com.usebottles.bottles'
